---
title: 환자 진료 예약 플로우차트
---
flowchart TD
    Start{시작}:::startEnd --> Step1[앱/웹 접속]:::process
    Step1 --> Check1{로그인 여부}:::decision
    Check1 -- No --> Login[로그인/회원가입]:::exception
    Login --> Step3
    Check1 -- Yes --> Step3[진료과/의사 선택]:::process
    Step3 --> Step4[날짜/시간 선택]:::process
    Step4 --> Step5[증상/메모 입력]:::process
    Step5 --> Check2{예약 확인?}:::decision
    Check2 -- 취소 --> Cancel[수정/취소]:::exception
    Check2 -- 확인 --> Step7[예약 완료 처리]:::complete
    Step7 --> Step8["알림(SMS/Push) 발송"]:::complete
    Step8 --> End{완료}:::startEnd
